name: pdf_gen
description: Generate pdf files from video slideshows easily
version: 2.0.1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  path: ^1.7.0
  image: ^3.1.3
  process_run: any
  pdf: ^3.8.0
  image_compare: ^1.1.2
